### ISSUE TITLE
name conflict

### ISSUE THREAD

**Issue by ungoldman** [koopjs/esri-to-geojson#1]
Hello,

There's already a node module called `geojson` (see https://www.npmjs.com/package/geojson). The current readme and package.json seem to indicate that this repo is for that module. I would recommend changing the name of the project in `package.json` and the readme to something that isn't already taken in the npm registry if you plan to publish this.

:smile:

**Comment by jgravois** [comment]
my ocd is probably showing, but it's also weird that the repo uses camel case and not hyphens like the rest of the projects in the organization.

**Comment by benstoltz** [comment]
Fixed up the name conflict and swapped in hyphens. Sorry guys!

**Comment by ungoldman** [comment]
💯  thanks dude

**Comment by jgravois** [comment]
55d3295 has an additional fix that i wish i'd caught before i released this morning.
