### ISSUE TITLE
README needs to clarify exactly what differentiates it from similar projects

### ISSUE THREAD

**Issue by jgravois** [koopjs/esri-to-geojson#2]
at first glance it looks like this repo is a library which wraps `arcgis-to-geojson-utils` that intends to make it really convenient to also just pass a .csv and get GeoJSON.  it would be helpful if the documentation was more explicit about this (and perhaps even included a sample with dummy data).

its certainly not entirely the fault of the library here, but its up to us to help our users wade through the various code that we've published so that they can quickly find the most appropriate tool.  this is complicated by the fact that we've published lots of _somewhat_ duplicative work.
- https://github.com/koopjs/esri-to-geojson
- https://github.com/Esri/arcgis-to-geojson-utils
- https://github.com/Esri/terraformer-arcgis-parser
- https://github.com/Esri/geojson-utils
- https://github.com/Esri/esri-to-geojson

see Esri/geojson-utils#16 for more info.

**Comment by dmfenton** [comment]
The biggest difference is that we translate more than the geometry. We actually make changes to the fields. These features are requirements of ArcGIS Open Data. I think we'd be happy to merge this project with another as long as these requirements are fulfilled and there is no significant performance degradation. 
- decoding domains
- creating x&y fields from csvs
- translating date fields to be human readable text

**Comment by jgravois** [comment]
i hadn't considered the possibility of trying to incorporate this work during a refactor of `terraformer-arcgis-parser` (discussed in Esri/Terraformer#268), but talking about it definitely makes sense.

**Comment by dmfenton** [comment]
I think we'd be happy with that. Until then, however, we'll need to move forward with this package so we can keep moving forward on the Koop 3.0 roadmap. Specifically hollowing out the lib directory.

**Comment by jgravois** [comment]
> we'll need to move forward with this package...

_totally_ fine.
i only meant to point out that clarifying the purpose of the project in the README would go a long way.

**Comment by dmfenton** [comment]
I agree, we should make a bunch of improvements to the readme including this one. We should also find a way to 🔪  this project because I don't wanna maintain it 😄

**Comment by jgravois** [comment]
the new disclaimer text in the readme is good nuff for me.
